### ISSUE TITLE
Default models won't display ever again after crash

### ISSUE THREAD

**Issue by EmmaCarro** [UnrealKaraulov/newbspguy#70] opened 2023-07-08 04:55 UTC
When manipulating textures with the Face Editor, if done long enough, sometimes newbspguy crashes. But after that happens, the default models won't display ever again (custom ones do). Whatever is done, resetting settings, downloading newbspguy again, changing the settings, won't work.
I managed to make it work again once, but I don't remember how exactly.

**Comment by UnrealKaraulov** [comment] 2023-12-05 14:37
@EmmaCarro default models?

**Comment by EmmaCarro** [comment] 2023-12-06 02:29
yes the models in svencoop/ folder won't load. Only the ones in svencoop_addon/

**Comment by UnrealKaraulov** [comment] 2023-12-06 06:49
@EmmaCarro in latest build this issue fixed?

**Comment by Qwertyus3D** [comment] 2023-12-06 16:49
> yes the models in svencoop/ folder won't load. Only the ones in svencoop_addon/

I think you have to check the order of enabled resources (Asset Paths in Settings). I bet you have the svencoop/ folder as the first entry, and svencoop_addon/ as the next entry. So all models from svencoop/ are just replaced with contains of svencoop_addon/

It's not a bug, it's how the things work. Edit the order to have the folder with desirable resources last in the list of assets.

**Comment by EmmaCarro** [comment] 2023-12-07 18:53
> > yes the models in svencoop/ folder won't load. Only the ones in svencoop_addon/
> 
> I think you have to check the order of enabled resources (Asset Paths in Settings). I bet you have the svencoop/ folder as the first entry, and svencoop_addon/ as the next entry. So all models from svencoop/ are just replaced with contains of svencoop_addon/
> 
> It's not a bug, it's how the things work. Edit the order to have the folder with desirable resources last in the list of assets.

Not whats happening, read the first post again. Everything works until newbspguy crashes when using the face editor too much. After that point, any default model in svencoop/ folder is not displaying no matter what you change in the settings or restart them. The only way to fix it is to redownload the newbspguy .exe again, its like it gets corrupted.

**Comment by Qwertyus3D** [comment] 2023-12-07 19:28
It's just too strange, I also have svencoop/ & svencoop_addon/ folders in my settings (and not only them) and never experienced any problems like these after any crash. And there is no sense why "using the face editor too much" has to be involved there. Just check that you have all the Asset Paths in Settings widget properly set and marked with checkbox (which makes them active) and press "Apply settings". Most probable, that you're getting some checkboxes missing here, and that's the reason why assets are not loaded.

**Comment by EmmaCarro** [comment] 2023-12-08 01:31
> It's just too strange, I also have svencoop/ & svencoop_addon/ folders in my settings (and not only them) and never experienced any problems like these after any crash. And there is no sense why "using the face editor too much" has to be involved there. Just check that you have all the Asset Paths in Settings widget properly set and marked with checkbox (which makes them active) and press "Apply settings". Most probable, that you're getting some checkboxes missing here, and that's the reason why assets are not loaded.

To reproduce the specific crash you need to start using the face editor's rotations and also be replacing textures on faces quickly. Although its been a while since this happened, maybe it has been fixed by proxy of another fix since newbspguy was updated not too long ago, but I don't know. 
Anyway although when this happened was a bit annoying I think the existance itself of newbspguy more than outweights the problem and has been the number 1 ripent tool so far .

**Comment by Qwertyus3D** [comment] 2023-12-17 19:52
Думаю, тоже нужно закрыть, не видно чётких пояснений - "иногда" крашится если "слишком много" пользоваться лайтмапером, и от этого становятся недоступными модели (Карл!) в какой-то папке. По-моему, крайне мутное описание, больше указывающее на то, что у юзера лапки и туман в голове. :D

**Comment by UnrealKaraulov** [comment] 2023-12-17 19:56
@EmmaCarro problem fixed in latest build?

**Comment by UnrealKaraulov** [comment] 2023-12-18 13:10
@EmmaCarro tell me here if problem not fixed in latest build.

**Closed as completed by UnrealKaraulov** 2023-12-18 13:10 UTC
Labels: bug, help wanted

**Comment by EmmaCarro** [comment] 2023-12-18 23:56
I think it is, I haven't crashed yet. I will ask again if it ever crashes again. It's difficult to reproduce anyway so don't worry that much
